<?php

use function Livewire\Volt\{title};

title('Cisco - Übersicht');

?>

<x-intranet-app-cisco::cisco-layout heading="Cisco App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-cisco::cisco-layout>